# Generated by Django 4.0.6 on 2022-07-13 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('societe', '0004_alter_mail_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mail',
            old_name='status',
            new_name='résolu',
        ),
    ]
