# Generated by Django 4.0.6 on 2022-07-14 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societe', '0005_rename_status_mail_résolu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='subject',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='mail',
            name='user',
            field=models.EmailField(max_length=254),
        ),
    ]
