# Generated by Django 4.0.6 on 2022-07-15 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('societe', '0006_alter_mail_subject_alter_mail_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mail',
        ),
    ]
