# Generated by Django 4.0.6 on 2022-07-18 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societe', '0008_message_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.CharField(default=0, max_length=1000000),
            preserve_default=False,
        ),
    ]
