# Generated by Django 4.0.6 on 2022-07-18 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('societe', '0009_message_sender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
    ]
